apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: jeffshenrique/kub-demo-tasks:latest
        env:
          - name: AUTH_ADDRESS
            # value: "10.107.20.229"
            value: "auth-service.default" ## service name + namespace
          - name: TASKS_FOLDER
            value: tasks
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>